import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {SocketProvider} from "../context/SocketProvider";//To wrap the whole app in this socket provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <SocketProvider> {/*Wrapping the whole app in this socket provider so that now we have full access to socketprovider*/}
      <body className={inter.className}>{children}</body>
      </SocketProvider>
    </html> 
  );
}
